version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_mini_app
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_BOT_TOKEN=your-telegram-bot-token
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_SOURCE=postgresql://root:secret@localhost:5432/simple_telegram?sslmode=disable
      - DB_NAME=simple_telegram
    depends_on:
        - db
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_telegram
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: