// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: service_tap.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TapService_ClickToEarn_FullMethodName = "/pb.TapService/ClickToEarn"
	TapService_GetUser_FullMethodName     = "/pb.TapService/GetUser"
)

// TapServiceClient is the client API for TapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TapServiceClient interface {
	ClickToEarn(ctx context.Context, in *ClickToEarnRequest, opts ...grpc.CallOption) (*ClickToEarnResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type tapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTapServiceClient(cc grpc.ClientConnInterface) TapServiceClient {
	return &tapServiceClient{cc}
}

func (c *tapServiceClient) ClickToEarn(ctx context.Context, in *ClickToEarnRequest, opts ...grpc.CallOption) (*ClickToEarnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClickToEarnResponse)
	err := c.cc.Invoke(ctx, TapService_ClickToEarn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, TapService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TapServiceServer is the server API for TapService service.
// All implementations must embed UnimplementedTapServiceServer
// for forward compatibility.
type TapServiceServer interface {
	ClickToEarn(context.Context, *ClickToEarnRequest) (*ClickToEarnResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	mustEmbedUnimplementedTapServiceServer()
}

// UnimplementedTapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTapServiceServer struct{}

func (UnimplementedTapServiceServer) ClickToEarn(context.Context, *ClickToEarnRequest) (*ClickToEarnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClickToEarn not implemented")
}
func (UnimplementedTapServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedTapServiceServer) mustEmbedUnimplementedTapServiceServer() {}
func (UnimplementedTapServiceServer) testEmbeddedByValue()                    {}

// UnsafeTapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TapServiceServer will
// result in compilation errors.
type UnsafeTapServiceServer interface {
	mustEmbedUnimplementedTapServiceServer()
}

func RegisterTapServiceServer(s grpc.ServiceRegistrar, srv TapServiceServer) {
	// If the following call pancis, it indicates UnimplementedTapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TapService_ServiceDesc, srv)
}

func _TapService_ClickToEarn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickToEarnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapServiceServer).ClickToEarn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TapService_ClickToEarn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapServiceServer).ClickToEarn(ctx, req.(*ClickToEarnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TapService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TapService_ServiceDesc is the grpc.ServiceDesc for TapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TapService",
	HandlerType: (*TapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClickToEarn",
			Handler:    _TapService_ClickToEarn_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _TapService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_tap.proto",
}
